# Generated by Django 2.2.4 on 2021-01-11 13:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_posts_dateandtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='dateAndTime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
