# Generated by Django 2.2.4 on 2021-01-29 04:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='followerID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='followerList', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profile',
            name='followers',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='following',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='followingID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='followingList', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profile',
            name='postID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='network.Posts'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profileOwner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
