# Generated by Django 2.2.4 on 2021-02-01 05:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_auto_20210129_0951'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='followerID',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='followingID',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='postID',
        ),
        migrations.CreateModel(
            name='FollowingList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followingID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='followingList', to=settings.AUTH_USER_MODEL)),
                ('listOwner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='listOwnerFIng', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FollowerList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followerID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='followerList', to=settings.AUTH_USER_MODEL)),
                ('listOwner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='listOwnerF', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
