# Generated by Django 2.2.4 on 2021-02-08 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0009_likeslist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likeslist',
            name='post_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='network.Posts'),
        ),
    ]
