# Generated by Django 2.2.4 on 2021-02-09 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0010_auto_20210208_1145'),
    ]

    operations = [
        migrations.RenameField(
            model_name='likeslist',
            old_name='post_id',
            new_name='idForPost',
        ),
        migrations.AlterField(
            model_name='likeslist',
            name='idForPost',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='network.Posts'),
        ),
    ]
