# Generated by Django 2.2.4 on 2021-02-09 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0013_auto_20210209_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likeslist',
            name='idForPost',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='network.Posts'),
        ),
    ]
